remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Vaishak\ Prasad 
description: Resources.![cursor](https://github.com/vaishakp/vaishakp.github.io/blob/a14b4054e00f1ce2fc2d746ac7283dd8b4d782bb/images/Flickering_cursor.gif)
