#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/minimal
#remote_theme: andrewbanchich/massively-jekyll-theme
remote_theme: andrewbanchich/future-imperfect-jekyll-theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Vaishak\ Prasad 
description: Resources.<img src="images/Flickering_cursor.gif" width="20"/>
